### ISSUE TITLE
cannot run the android project

### ISSUE THREAD

**Issue by OsamaDroidEgypt** [nickbutcher/plaid#323]
Android resource linking failed
Output:  C:\Users\OsMat\Documents\GitHub\plaid\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:2987: error: style attribute 'attr/maxExpandedTextSize (aka io.plaidapp:attr/maxExpandedTextSize)' not found.
C:\Users\OsMat\Documents\GitHub\plaid\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:2988: error: style attribute 'attr/titleInsetStart (aka io.plaidapp:attr/titleInsetStart)' not found.
C:\Users\OsMat\Documents\GitHub\plaid\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:2989: error: style attribute 'attr/titleInsetTop (aka io.plaidapp:attr/titleInsetTop)' not found.
C:\Users\OsMat\Documents\GitHub\plaid\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:2990: error: style attribute 'attr/titleInsetEnd (aka io.plaidapp:attr/titleInsetEnd)' not found.
C:\Users\OsMat\Documents\GitHub\plaid\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:2991: error: style attribute 'attr/titleInsetBottom (aka io.plaidapp:attr/titleInsetBottom)' not found.
error: failed linking references.

Command: C:\Users\OsMat\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.0-alpha18-4804415-windows.jar\1f0f8c612ce8afab4ef9532397d53e77\aapt2-3.2.0-alpha18-4804415-windows\aapt2.exe link -I\
        C:\Users\OsMat\AppData\Local\Android\Sdk\platforms\android-28\android.jar\
        --manifest\
        C:\Users\OsMat\Documents\GitHub\plaid\app\build\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
        -o\
        C:\Users\OsMat\Documents\GitHub\plaid\app\build\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
        -R\
        @C:\Users\OsMat\Documents\GitHub\plaid\app\build\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
        --auto-add-overlay\
        --java\
        C:\Users\OsMat\Documents\GitHub\plaid\app\build\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
        --custom-package\
        io.plaidapp\
        -0\
        apk\
        -c\
        en\
        --output-text-symbols\
        C:\Users\OsMat\Documents\GitHub\plaid\app\build\intermediates\symbols\debug\R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.0-alpha18-4804415-windows Daemon #0

**Comment by tiembo** [comment]
I believe this was fixed by #318.  Are you building against the latest version of the master branch?

**Comment by OsamaDroidEgypt** [comment]
@tiembo  no I build with latest version of the master branch

**Comment by tiembo** [comment]
Can you describe your setup?  Running via command line, Android Studio (and version number), etc?

**Comment by keyboardsurfer** [comment]
There were a lot of structural changes recently in the project.
Make sure to clear gradle caches before trying to build again (located in the `.gradle` folder in the project root).

**Comment by keyboardsurfer** [comment]
@OsamaDroidEgypt can you confirm this issue still occurs after completing the above steps?

**Comment by XinyueZ** [comment]
I see `3.2.0-alpha18`  on the bottom lines of output, I think it could be the problem of the old version of gradle plugin.
I use `gradle-3.3.0-alpha03` which is exactly equaled by the project default and it works.
My suggestion is to replace with the new gradle plugin.

**Comment by tiembo** [comment]
Closing stale issue - please reopen if this is still happening.
